services:
  backend:
    image: docker-backend
    container_name: docker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "8000:8000"

  frontend:
    image: docker-frontend
    pull_policy: never
    container_name: docker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
