services:
  backend:
    image: docker-backend
    container_name: docker-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: docker-frontend
    pull_policy: never
    container_name: docker-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mongodb:
    image: mongo:7.0.12
    container_name: docker-mongodb
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./mongodb/.env

volumes:
  mongodb-data:
